apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hes-extensions
  namespace: gitops-wr
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'