apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'app-1'
  namespace: 'gitops-wr'
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: hes-extensions
  source:
    path: 'dev'
    repoURL: 'https://github.com/3lvia/hes-extensions-demo.git'
    targetRevision: HEAD
  project: 'hes-extensions'